ALTER TABLE part_Table
PARTITION BY RANGE (EngineClass) (
	PARTITION p00 VALUES LESS THAN (20),
	PARTITION p01 VALUES LESS THAN (40),
	PARTITION p02 VALUES LESS THAN (60),
	PARTITION p03 VALUES LESS THAN (80),
	PARTITION p04 VALUES LESS THAN (100),
	PARTITION p05 VALUES LESS THAN (120),
	PARTITION p06 VALUES LESS THAN MAXVALUE
);